BOT_TOKEN = "8995798622:AAGufN8J5PiZzCqujAILqe-fFbU2wuvhw5Y"
SUPER_ADMIN_ID = 7982614573

CHAT_URL = "https://t.me/your_chat_link"
CHANNEL_URL = "https://t.me/your_channel_link"

YOUTUBE_URL = ""
INSTAGRAM_VITALIY = ""
INSTAGRAM_LYUBASHKA = ""
TIKTOK_VITALIY = ""
TIKTOK_LYUBASHKA = ""

DONATE_CARD = ""
DONATE_KASPI = ""
DONATE_BOOSTY = ""
DONATE_OTHER = ""

DB_NAME = "bot_database.db"

AI_API_KEY = ""
AI_MODEL = "gpt-3.5-turbo"

MAX_BOOKS_PER_PAGE = 20
LOG_LIMIT = 100
BROADCAST_DELAY = 0.05

CHAT_ID = -1004480019939