server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/slavyanochka;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(mp3|jpg|jpeg|png|webp|css|js)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript;
}
